### ISSUE TITLE
Replace the webbrowser

### ISSUE THREAD

**Issue by asokero** [opinsys/iivari#10] opened 2011-12-20 13:25 UTC
Chromium seems to be unstable in a long term use, causing the slide presentation-tab to occationally crash. There is a simplified browser available and it could be used to replace chromium.

**Comment by juhaerk** [comment] 2012-01-18 14:22
This issue is a duplicate of liitu-puppet#87, which is resolved.

**Closed as completed by juhaerk** 2012-01-18 14:22 UTC
